#pragma once

#include <devioctl.h>

#define CAT_BJT_DEVICE_TYPE 0x8337
#define IOCTL_CAT_BJT_READ CTL_CODE(CAT_BJT_DEVICE_TYPE, 0x800, METHOD_BUFFERED, FILE_READ_ACCESS)

#define CAT_BJT_PROTOCOL_VERSION 1U
#define CAT_BJT_SENSOR_COUNT 6U

typedef struct _CAT_BJT_READ_RESPONSE {
    ULONG Version;
    ULONG Size;
    ULONG Bar0Low;
    ULONG Bar0High;
    ULONG ValidMask;
    ULONG Raw[CAT_BJT_SENSOR_COUNT];
} CAT_BJT_READ_RESPONSE, *PCAT_BJT_READ_RESPONSE;
